definitions:
  Product:
    description: products defined for the product API
    properties:
      amount:
        format: int64
        type: integer
        x-go-name: Amount
      id:
        description: the id of the user
        format: int64
        minimum: 1
        type: integer
        x-go-name: ID
      name:
        type: string
        x-go-name: Name
      sku:
        type: string
        x-go-name: SKU
    required:
    - id
    type: object
    x-go-package: prod-api/data
info: {}
paths:
  /products:
    get:
      description: it returns a list of products
      operationId: listProducts
      responses:
        "200":
          $ref: '#/responses/productsResponse'
      tags:
      - products
    post:
      description: Create a new product
      operationId: createProduct
      responses:
        "200":
          $ref: '#/responses/productResponse'
        "422":
          $ref: '#/responses/errorValidation'
        "501":
          $ref: '#/responses/errorResponse'
      tags:
      - products
    put:
      description: Update a products details
      operationId: updateProduct
      responses:
        "201":
          $ref: '#/responses/noContentResponse'
        "404":
          $ref: '#/responses/errorResponse'
        "422":
          $ref: '#/responses/errorValidation'
      tags:
      - products
  /products/{id}:
    delete:
      description: it deletes a products from database
      operationId: deleteProducts
      responses:
        "201":
          $ref: '#/responses/noContent'
      tags:
      - products
responses:
  noContent:
    description: ""
  productsResponse:
    description: A list of products returns in the response
    schema:
      items:
        $ref: '#/definitions/Product'
      type: array
swagger: "2.0"
